### ISSUE TITLE
IDEA error?

### ISSUE THREAD

**Issue by KazuyaWaga** [ynupc/scalastringcourseday5#2]
Project JDK is not defined

**Comment by ynupc** [comment]
"File" -> "Project Structure" -> "Project Settings"の"Project" -> "Project SDK"がJDK1.8に設定されているか確認してみてください。

**Comment by ynupc** [comment]
"File" -> "Project Structure" -> "Project Settings"の"Modules" -> "Dependencies"の"Module SDK"をJDK1.8に設定するか、
.idea/を削除してもう一度プロジェクトをimportすると直りました。
